services:
  kotlinapp:
    container_name: kotlinapp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: jdbc:postgresql://db:5432/postgres
        PG_USER: postgres
        PG_PASSWORD: postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
volumes:
  pgdata: {}


